# Site settings
title: William Godfree
email: william@williamgodfree.co.uk


# Build settings
markdown: kramdown
theme: minima

minima:
  social_links:
    twitter: williamgodfree
    facebook: williamgodfreemusic
    instagram: williamgodfreemusic
    linkedin: william-godfree-452a8358
