# Site settings
title: William Godfree
email: william@williamgodfree.co.uk

# Theme settings
minima:
  social_links:
    twitter: williamgodfree
    facebook: williamgodfreemusic
    instagram: williamgodfreemusic
    linkedin: william-godfree-452a8358

# Build settings
markdown: kramdown
theme: minima
