# Site settings
title: William Godfree
email: william@williamgodfree.co.uk

header_pages:
  - latestnews.md
  - performer.md
  - composer.md
  - archive.md
  - media.md
  - shop.md
  - contact.md

# Theme settings
twitter_username: williamgodfree
facebook_username: williamgodfreemusic
instagram_username: williamgodfreemusic
linkedin_username: william-godfree-452a8358

google_analytics: UA-170647982-2

# Build settings
markdown: kramdown
theme: minima
