# Site settings
title: William Godfree - Under Construction
email: william@williamgodfree.co.uk
description: > 
  William Godfree website - under construction


# Build settings
markdown: kramdown
theme: minima
